### PR TITLE
Added notes to the README.md

### PR DESCRIPTION
**Pull request by HARI-PRMD**

### CODE REVIEW

**Review by floyrin — APPROVED** [review]
amazing

**Review by joshi-hahahaha — COMMENTED** [review]
I think one small thing (and I'm not sure if this is true or not) but viteJS might be different to viteTS? 

I was just looking through vite vaguely on my own and there might've been distinction between the two.

OLD: I'll approve and if it is meant to be viteTS then change it if it bugs you. If not you can leave it 😎

NEW: Actually Jane merged this as I was typing this 😞

**Comment by floyrin** [comment]
OOPSIE

**Comment by HARI-PRMD** [comment]
💀 actually so doomed surely we can just commit another small change right?

**Pull request merged**
